# Generated by Django 5.1.4 on 2025-01-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Social', 'Social'), ('Workshop', 'Workshop'), ('Meetup', 'Meetup'), ('Conference', 'Conference'), ('Other', 'Other')], max_length=50),
        ),
    ]
